baseURL = "https://vesper.netlify.app/"
languageCode = "en-us"
summaryLength = 25
enableRobotsTXT = "true"
[outputs]
home = ["HTML", "RSS", "JSON"]
[taxonomies]
category = "categories"
cities = "cities"
featured = "featured"
properties = "properties"
states = "states"
status = "status"
tag = "tags"